### ISSUE TITLE
PX4 v1.11 Release Checklist

### ISSUE THREAD

**Issue by mrpollo** [PX4/PX4-Autopilot#15537]
In order to get the PX4 v1.11 release out the door, we need to get a few remaining issues closed, we are going to try to keep track of them here since they don't really require their own issue, as there's no commits going towards the PX4/Firmware codebase.

* [x] [Release Testing](https://discuss.px4.io/t/px4-v1-11-release-candidate-is-here-open-call-for-testing/18015)
* [x] [Updated Release Notes](https://github.com/PX4/Firmware/issues/14402)
* [ ] Blog Post on PX4.io

Let me know if I missed anything below.
