### ISSUE TITLE
[Project Tracker] Control Allocation User experience improvement

### ISSUE THREAD

**Issue by junwoo091400** [PX4/PX4-Autopilot#19444]
## Description
This is an issue to track tasks & have discussions on improving the Control Allocation user experience. I previously had a google doc to keep these tracked, but now making it public on Github repo to make it more transparent!

### Why
The Control Allocation is already implemented : #18776 and after the upcoming release of PX4 v1.13.0, it will be the main controller. So making the user experience as smooth as possible is important, so that every user can set it up without confusion.

## PRs from this Project
* User Doc : https://github.com/PX4/PX4-user_guide/pull/1858 
* Autopilot : https://github.com/PX4/PX4-Autopilot/pull/19606

## TODOs
- [x] Autopilot : Add 'hz' indicator to PWM 50, PWM 100, etc selections in Actuators tab to avoid confusion on what those numbers mean
- [x] Doc : Add Description on Control Surface
- [x] Doc : Add 'Center of Gravity' diagram to show where the distance measurement reference point is (It's not the Pixhawk's center!!!)
- [x] Doc : Add Description on setting 1500 as Servo's disarmed PWM output value to avoid weird motions
- [x] Doc : For VTOL / Fixed Wing : Add description for enabling 'lock control surface to hover' and 'commander prearm' settings, to properly check trimmed servo outputs.
- [ ] Doc : Add description on the 'Json' file being transferred from PX4 to QGC, describing actuators setup, to explain what 'dynamic loading' of Actuators configuration actually means
- [ ] Doc : Provide the list of control surface **types** (e.g. Aileron, Elevon, Elevator, etc.) and explain them
- [ ] Doc : Provide more thorough control surface geometry setup doc (Right now **only** the '[Motor](https://docs.px4.io/master/en/config/actuators.html#motor-geometry-vtol-tiltrotor)' setup part has Multicopter / VTOL configuration examples)
- [ ] Doc : Create individual docs for each vehicle types to explain specific configurations to supplement a generic [Geometry](https://docs.px4.io/master/en/config/actuators.html#geometry) explanation.
  - [ ] Multicopter
  - [ ] VTOL
  - [ ] Fixed Wing
- [ ] QGC : Put warning 'pop up' when user inputs a value (e.g. Roll torque input for Left Elevon ...) that doesn't make sense according to control surface convention, to avoid user confusions
- [ ] QGC : Add support for basic fixed wing /  rover graphics for Actuators tab (currently only multi-copters are visualized)
- [ ] QGC : Fix bug on initial graphics of multicopter not showing anything when motor positions are (0,0)
- [ ] QGC : Make trim part click-adjustable, e.g. by a unit of 0.05 or so.
- [ ] QGC : Add Visual Support for multiple vehicle types (for easier configuration)
  - [ ] VTOL : Urgent!
  - [ ] Fixed Wing

## Relevant Links
* [Initial Control Allocation tryout notes from Junwoo](https://docs.google.com/document/d/1C3Td23R3OoXiBlMKtnVjekwS_zitxI4d1hSpJ0ENvxs/edit?usp=sharing) - Google Docs (Now not updated!)
* [Control Allocation proposal google doc - provided by Hamish (PX4 Mixing Rework)](https://docs.google.com/document/d/10WsNyjARZEuDeCNywnwBnUy3FhX4CR2fmSL0b4eZl6U/edit#heading=h.8g8ygrtolpw8)
* User Guide
  * https://docs.px4.io/master/en/config/actuators.html
  * https://docs.px4.io/master/en/dev_airframes/adding_a_new_frame.html
  * https://docs.px4.io/master/en/concept/mixing.html
  * https://docs.px4.io/master/en/concept/geometry_files.html
    * https://github.com/PX4/PX4-Autopilot/tree/master/src/lib/mixer/MultirotorMixer/geometries
  * https://github.com/PX4/PX4-user_guide/pull/1704
* PX4-Autopilot
  * https://github.com/PX4/PX4-Autopilot/pull/13351
  * Initial Configurable Actuator output control PR : https://github.com/PX4/PX4-Autopilot/pull/16808
  * https://github.com/PX4/PX4-Autopilot/pull/18265
  * https://github.com/PX4/PX4-Autopilot/pull/18776
  * https://github.com/PX4/PX4-Autopilot/pull/19193
  * https://github.com/PX4/PX4-Autopilot/pull/16528
  * https://github.com/PX4/PX4-Autopilot/pull/19596

**Comment by Jaeyoung-Lim** [comment]
@junwoo091400 There is actually a fixedwing model in Gazebo SITL missing for control allocation. Would be great if we can have this as an example as part of this :smile:

**Comment by junwoo091400** [comment]
If you could point me to where I could check, that would be great! @Jaeyoung-Lim

**Comment by Jaeyoung-Lim** [comment]
@junwoo091400 We can currently test control allocation models in SITL with the following two models: https://github.com/PX4/PX4-Autopilot/tree/master/ROMFS/px4fmu_common/init.d-posix/airframes

- [10017_iris_ctrlalloc](https://github.com/PX4/PX4-Autopilot/blob/master/ROMFS/px4fmu_common/init.d-posix/airframes/10017_iris_ctrlalloc)
- [6012_typhoon_h480_ctrlalloc](https://github.com/PX4/PX4-Autopilot/blob/master/ROMFS/px4fmu_common/init.d-posix/airframes/6012_typhoon_h480_ctrlalloc)

However, we are missing a fixedwing model as an example

**Comment by bkueng** [comment]
@Jaeyoung-Lim you can enable it here: https://github.com/PX4/PX4-Autopilot/blob/master/ROMFS/px4fmu_common/init.d-posix/airframes/1030_plane#L46=

**Comment by junwoo091400** [comment]
Control Surfaces & Servo Documentation done in https://github.com/PX4/PX4-user_guide/pull/1858/commits/a81088a3c65bfa18632c7fcf8bbe6045f9070f55

**Comment by junwoo091400** [comment]
Added TODOs on Control Surface explanation, as the [user ](https://px4.slack.com/archives/C581ST17V/p1654864120332779?thread_ts=1654863386.548499&cid=C581ST17V)was having trouble setting it up

![image](https://user-images.githubusercontent.com/23277211/173065616-0349b21a-4343-4278-9fba-40ae4e62f227.png)

**Comment by Tiktiki** [comment]
Rebuilding a Gen1 Firefly6 and I was looking at the geometry settings.
Are the values (in meters) from the CG or from the IMU?
On this specific airframe both are relatively close, but this is a stepping stone to a fully custom VTOL I am working on.

ALSO

Having the ability to select which servo/gear output gets enable in pre-arm would be great. I have issues with landing gears moving when already set in pre-arm. For example I have a plane with gear that can be catapult-launched or take-off from a runway. Depending on the situation the gear need to be up or down at pre-arm/arming.

**Comment by junwoo091400** [comment]
A lot of the QGC improvements would be possible after my Frames metadata QGC PR goes in, as I would have way more Qt knowledge & good idea on how to implement the changes in the TODO list 😉 

https://github.com/mavlink/qgroundcontrol/pull/10472
