### ISSUE TITLE
[Project Tracker] Sensor Calibration Improvement for PX4

### ISSUE THREAD

**Issue by junwoo091400** [PX4/PX4-Autopilot#19459]
## Why
Currently, Sensor calibrations are really tedious, especially the 6-point magnetometer calibration dance you need to do in the field. This is cumbersome and inconvenient. Also, whenever you calibrate a sensor, you need to specify the mounting orientation, which is really confusing (e.g. Calibrating the Internal Magnetometer requires you to set the orientation in QGC, why?).

Sensor Calibration should become much simpler.

## Goal of the Project
1. **Remove 6 point Mag dance & Acc calibration routine, or dramatically simplify it**
2. Unify Sensor Calibration so that the user can just push one button and **calibrate everything at once**
3. **Clearly define Sensor orientation rules** (Is it in reference to the Board? the Gravity? etc)
4. Make Automatic Sensor Orientation detection work seamlessly ([Currently it can return false values](https://discuss.px4.io/t/px4-dev-call-april-06-2022/26787#sensor-calibration-improvements-junwoo0914-12))
6. **Allow arbitrary sensor mount orientation** (No hard rules like Roll 0, Pitch 270, etc.)

## Related Links
- There already exists a "quick cal" for Magnetometer, which compensates for any external magnetic disturbance using gyro data : #16413 & #18327. This improves user experience significantly. However, the 6 point dance is still necessary.
- Repository where the scripts used for the sensor cal improvements are stored : https://github.com/junwoo091400/PX4-Sensor-Calibration
- https://github.com/PX4/PX4-Autopilot/pull/13623
- https://github.com/mavlink/qgroundcontrol/pull/9217
- https://github.com/PX4/PX4-Autopilot/pull/16293/commits/b473922b5a34eb0293f3ca98db53598931b2c20f
- 

## TODOs
- [ ] Understand current sensor calibration architecture
- [ ] Discuss ideas on how to achieve these goals above, with stakeholders
- [ ] The ‘wireless sensor calibration can be unstable’ message -> remove this message! as [discussed in the dev-call.](https://discuss.px4.io/t/px4-dev-call-april-20-2022/26970)
- [ ] The diagrams for mag calibration are ambiguous. Change it to 'dotted circle' to show that vehicle doesn't need to be turned in a certain direction
- [ ] Change the QGC diagram to a GIF that shows the drone actually swiveling, for more intuitive calibration process
- [ ] Refactor calibration folder and move it into sub folders of commander
- [ ] Refactor to use 'Event' message to indicate calibration status, instead of publishing mavlink message / status_mag messages to the QGC (Which is the reason why it can be unreliable to use Wireless connection to do MAG cal)
- [ ]

**Comment by chris1seto** [comment]
One comment: For sensor alignment, the presets are actually helpful because the alternative is having to manually input a rotation matrix, which might be confusing for users. Perhaps there could be some presets in qgc or just the ability to enter a raw quat. The actual param might be a quat, I'm just suggesting covering it in the front end unless the user wants to specify it themselves.

**Comment by ryanjAA** [comment]
@junwoo091400 this is so very needed. 👍👍👍

**Comment by junwoo091400** [comment]
Suggestion from @chris1seto from [Slack](https://px4.slack.com/archives/C50RWGQMT/p1649430999304469?thread_ts=1649421934.662239&cid=C50RWGQMT)

> One suggestion I would have is for there to be an easy way to export/import calibration parameters only. I realize this might be more of a qgc than Px4 feature, but the **single worst part of doing a parameter reset for me is redoing calibration because I don't have a way of only reloading calibration params only.** I realize there might be some editing of a normal parameter export that's possible, I just mean that there is no standard way of doing this.

**Comment by junwoo091400** [comment]
Input from @cmic0 :
1. Would be nice to have a voice saying "stop", or "turn", when doing calibration, not just a diagram showing what to do
2. Change the diagram from Fixed Wing to Copter :thinking: 
3. We only need to do 6 point mag dance once, so it's not really cumbersome.

**Comment by junwoo091400** [comment]
Added 2 TODOS from the last dev call : https://discuss.px4.io/t/px4-dev-call-april-20-2022/26970

**Comment by ryanjAA** [comment]
Option for copter (checkbox?) or fixed wing icon since both are used makes more sense than one or the other since both are used and relevant.

**Comment by junwoo091400** [comment]
> One comment: For sensor alignment, the presets are actually helpful because the alternative is having to manually input a rotation matrix, which might be confusing for users.

@chris1seto What do you mean by 'preset'? The ROTATION parameter of the sensors? 🤔
