### ISSUE TITLE
Feature TODO list for full Ignition Gazebo Support

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/PX4-Autopilot#20046]
## Describe problem solved by the proposed feature
Currently ignition gazebo only supports a minimal version of a quadrotor model. We would like to fully support ignition gazebo as the primary simulation for px4 sitl.

The following list outlines the work packages that needs to be ported over to support ignition gazebo @dagar

### Utilities
- [ ] Camera manager plugin

### Models
- [ ] Gimbal Controller and gimbal models
- [ ] Parachute plugin
- [x] Lift drag plugin and

### Sensors
- [x] Airspeed sensors
- [ ] Distance(Lidar) Sensor
- [ ] Optical flow sensor
- [ ] IR Beacon

**Comment by SangwooJ** [comment]
@Jaeyoung-Lim  I am trying to add lidar(gpu_ray) to the x500 model in Gazebo(ignition) by following this instructions https://gazebosim.org/docs/garden/sensors . However, It is not working properly, the simulator stops and crashes. Is this a PX4 problem?

**Comment by Jaeyoung-Lim** [comment]
@SangwooJ I don't think so

**Comment by SangwooJ** [comment]
@Jaeyoung-Lim Thanks for the reply. Currently is it possible to add Lidar(gpu_ray) to the x500 in gazebo ignition(garden)?
