### ISSUE TITLE
[RFC] Split build targets per vehicle type

### ISSUE THREAD

**Issue by mrpollo** [PX4/PX4-Autopilot#23901]
In summary, we will be moving away from a default build target that fits all hardware, to a per vehicle type, eg:

**Current:**
* px4_fmu-v6x_default

**New:**
* px4_fmu-v6x_multicopter
* px4_fmu-v6x_fixedwing
* px4_fmu-v6x_vtol
* px4_fmu-v6x_boat
* ...etc...

We will also introduce a manifest.json file, with a list of all targets, this json file will live in S3.

Our hopes are that QGC fetches the manifest from S3, and builds a list of available options for the user.

Once the user selects what they want, they proceed with the firmware update.

QGC downloads the right files from S3, following the manifest.json, and then proceeds with the current firmware update
We need someone experienced in QGC 

## TODO
**PX4**
* [ ] Generate builds per vehicle target
* [ ] Generate manifest.json metadata
* [ ] Upload manifest and vehicel targets to S3

**QGC**
* [ ] Update PX4 update UI and introduce all the new options
* [ ] Build UI based on the manifest.json metadata file (downloaded from S3)

**Comment by DronecodeBot** [comment]
This issue has been mentioned on **Discussion Forum for PX4, Pixhawk, QGroundControl, MAVSDK, MAVLink**. There might be relevant details there:

https://discuss.px4.io/t/px4-sync-q-a-nov-6-2024/42264/1

**Comment by DronecodeBot** [comment]
This issue has been mentioned on **Discussion Forum for PX4, Pixhawk, QGroundControl, MAVSDK, MAVLink**. There might be relevant details there:

https://discuss.px4.io/t/px4-sync-q-a-dec-18-2024/42886/1
